config/routes.rb
Rails.application.routes.draw do
  #resources :asxlistings
  root "users#new"
  resources :users
  resources :listings



  #resources :users,:confirmations, only: [:create, :delete ]  #We only want to create/delete email addresses
  
  # We also need to cover incorrect URLs enterred.  Any path that isn't captured above
  # will get picked up here and sent to root.
  get '*path' => 'users#new'

  
end
 

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/asxlisting.rb
class Asxlisting < ApplicationRecord
end

app/models/listing.rb
class Listing < ApplicationRecord
end

app/models/user.rb
class User < ApplicationRecord
# Ensure that we only have one email address.  No duplicates    
#    validates :email, uniqueness: true
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/asxlistings_controller.rb
class AsxlistingsController < ApplicationController
  before_action :set_asxlisting, only: %i[ show edit update destroy ]

  # GET /asxlistings or /asxlistings.json
  def index
    @asxlistings = Asxlisting.order(:company) # Retrieve in alphabetical order 
  end

  # GET /asxlistings/1 or /asxlistings/1.json
  def show
  end

  # GET /asxlistings/new
  def new
    @asxlisting = Asxlisting.new
  end

  # GET /asxlistings/1/edit
  def edit
  end

  # POST /asxlistings or /asxlistings.json
  def create
    @asxlisting = Asxlisting.new(asxlisting_params)

    respond_to do |format|
      if @asxlisting.save
        format.html { redirect_to asxlisting_url(@asxlisting), notice: "Asxlisting was successfully created." }
        format.json { render :show, status: :created, location: @asxlisting }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @asxlisting.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /asxlistings/1 or /asxlistings/1.json
  def update
    respond_to do |format|
      if @asxlisting.update(asxlisting_params)
        format.html { redirect_to asxlisting_url(@asxlisting), notice: "Asxlisting was successfully updated." }
        format.json { render :show, status: :ok, location: @asxlisting }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @asxlisting.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /asxlistings/1 or /asxlistings/1.json
  def destroy
    @asxlisting.destroy

    respond_to do |format|
      format.html { redirect_to asxlistings_url, notice: "Asxlisting was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_asxlisting
      @asxlisting = Asxlisting.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def asxlisting_params
      params.require(:asxlisting).permit(:code, :company, :date, :listingPrice, :currentPrice)
    end
end

app/controllers/listings_controller.rb
class ListingsController < ApplicationController
  before_action :set_listing, only: %i[ show edit update destroy ]

  # GET /listings or /listings.json
  def index
    @listings = Listing.order(:company) #Retrieve listings in alphabetical order
  end

  # GET /listings/1 or /listings/1.json
  def show
  end

  # GET /listings/new
  def new
    @listing = Listing.new
  end

  # GET /listings/1/edit
  def edit
  end

  # POST /listings or /listings.json
  def create
    @listing = Listing.new(listing_params)

    respond_to do |format|
      if @listing.save
        format.html { redirect_to listing_url(@listing), notice: "Listing was successfully created." }
        format.json { render :show, status: :created, location: @listing }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @listing.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /listings/1 or /listings/1.json
  def update
    respond_to do |format|
      if @listing.update(listing_params)
        format.html { redirect_to listing_url(@listing), notice: "Listing was successfully updated." }
        format.json { render :show, status: :ok, location: @listing }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @listing.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /listings/1 or /listings/1.json
  def destroy
    @listing.destroy

    respond_to do |format|
      format.html { redirect_to listings_url, notice: "Listing was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_listing
      @listing = Listing.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def listing_params
      params.require(:listing).permit(:company, :listingDate, :contact, :activities, :price, :shareType, :code, :capital, :close, :underwriter)
    end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :set_user, only: %i[ show edit update destroy ]

  # GET /users/new
  def new
  #  User.delete_all
    @user = User.new
  end

  # GET /user/:id
  def show
  end

  # POST /users or /users.json
  def create
    # Check if the user exists and if so delete them else create them.  This is how we implement
    # the unsubscribe feature.
    if User.exists?(user_params)  
      User.destroy_by(user_params)
      redirect_to "/"
    else  
      @user = User.new(user_params)

      respond_to do |format|
        if @user.save        

          # Send an email saying welcome to the new user.  Send asynchronously via .deliver_later or send synchronously via .deliver_now
          # UserMailer is found in mailers/user_mailer.rb
          NotifierMailer.signup_confirmation(@user.email).deliver_later

          # Send the new user the latest newsletter.
          ListingMailer.listing(@user.email).deliver_later
          
          format.html { redirect_to "/" }
        else
          format.html { render :new, status: :unprocessable_entity }
          format.json { render json: @user.errors, status: :unprocessable_entity }
        end # if loop
      end # do loop  
    end # if loop
  end # create

  # DELETE 
  def destroy
    @user.destroy

    respond_to do |format|
      format.html { redirect_to "/", notice: "Sorry to see you go." }
      format.json { head :no_content }
    end
  end


  private
    # Use callbacks to share common setup or constraints between actions.
    def set_user
      @user = User.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def user_params
      params.require(:user).permit(:email)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/asxlistings_helper.rb
module AsxlistingsHelper
end

app/helpers/confirmations_helper.rb
module ConfirmationsHelper
end

app/helpers/listing_helper.rb
module ListingHelper
end

app/helpers/listings_helper.rb
module ListingsHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/asxlistings/_asxlisting.html.erb
<div id="<%= dom_id asxlisting %>">
  <p>
    <strong>Code:</strong>
    <%= asxlisting.code %>
  </p>

  <p>
    <strong>Company:</strong>
    <%= asxlisting.company %>
  </p>

  <p>
    <strong>Date:</strong>
    <%= asxlisting.date %>
  </p>

  <p>
    <strong>Listingprice:</strong>
    <%= asxlisting.listingPrice %>
  </p>

  <p>
    <strong>Currentprice:</strong>
    <%= asxlisting.currentPrice %>
  </p>

</div>

app/views/asxlistings/_form.html.erb
<%= form_with(model: asxlisting) do |form| %>
  <% if asxlisting.errors.any? %>
    <div style="color: red">
      <h2><%= pluralize(asxlisting.errors.count, "error") %> prohibited this asxlisting from being saved:</h2>

      <ul>
        <% asxlisting.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div>
    <%= form.label :code, style: "display: block" %>
    <%= form.text_field :code %>
  </div>

  <div>
    <%= form.label :company, style: "display: block" %>
    <%= form.text_field :company %>
  </div>

  <div>
    <%= form.label :date, style: "display: block" %>
    <%= form.text_field :date %>
  </div>

  <div>
    <%= form.label :listingPrice, style: "display: block" %>
    <%= form.text_field :listingPrice %>
  </div>

  <div>
    <%= form.label :currentPrice, style: "display: block" %>
    <%= form.text_field :currentPrice %>
  </div>

  <div>
    <%= form.submit %>
  </div>
<% end %>

app/views/asxlistings/edit.html.erb
<h1>Editing asxlisting</h1>

<%= render "form", asxlisting: @asxlisting %>

<br>

<div>
  <%= link_to "Show this asxlisting", @asxlisting %> |
  <%= link_to "Back to asxlistings", asxlistings_path %>
</div>

app/views/asxlistings/index.html.erb
<p style="color: green"><%= notice %></p>

<h1>Asxlistings</h1>

<div id="asxlistings">
  <% @asxlistings.each do |asxlisting| %>
    <%= render asxlisting %>
    <p>
      <%= link_to "Show this asxlisting", asxlisting %>
    </p>
  <% end %>
</div>

<%= link_to "New asxlisting", new_asxlisting_path %>

app/views/asxlistings/new.html.erb
<h1>New asxlisting</h1>

<%= render "form", asxlisting: @asxlisting %>

<br>

<div>
  <%= link_to "Back to asxlistings", asxlistings_path %>
</div>

app/views/asxlistings/show.html.erb
<p style="color: green"><%= notice %></p>

<%= render @asxlisting %>

<div>
  <%= link_to "Edit this asxlisting", edit_asxlisting_path(@asxlisting) %> |
  <%= link_to "Back to asxlistings", asxlistings_path %>

  <%= button_to "Destroy this asxlisting", @asxlisting, method: :delete %>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Subscription</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_importmap_tags %>
    
  </head>
  
  <style>
  body {
    background-image: url('IPOWatchlist3.jpg');   
    background-image: no-repeat;                  
    background-attachment: fixed;                 
    background-size: cover;                       
  }
  </style>

  <body>
    <%= yield %>
  </body>
</html>

app/views/listings/_form.html.erb
<%= form_with(model: listing) do |form| %>
  <% if listing.errors.any? %>
    <div style="color: red">
      <h2><%= pluralize(listing.errors.count, "error") %> prohibited this listing from being saved:</h2>

      <ul>
        <% listing.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div>
    <%= form.label :company, style: "display: block" %>
    <%= form.text_field :company %>
  </div>

  <div>
    <%= form.label :listingDate, style: "display: block" %>
    <%= form.text_field :listingDate %>
  </div>

  <div>
    <%= form.label :contact, style: "display: block" %>
    <%= form.text_field :contact %>
  </div>

  <div>
    <%= form.label :activities, style: "display: block" %>
    <%= form.text_field :activities %>
  </div>

  <div>
    <%= form.label :price, style: "display: block" %>
    <%= form.text_field :price %>
  </div>

  <div>
    <%= form.label :shareType, style: "display: block" %>
    <%= form.text_field :shareType %>
  </div>

  <div>
    <%= form.label :code, style: "display: block" %>
    <%= form.text_field :code %>
  </div>

  <div>
    <%= form.label :capital, style: "display: block" %>
    <%= form.text_field :capital %>
  </div>

  <div>
    <%= form.label :close, style: "display: block" %>
    <%= form.text_field :close %>
  </div>

  <div>
    <%= form.label :underwriter, style: "display: block" %>
    <%= form.text_field :underwriter %>
  </div>

  <div>
    <%= form.submit %>
  </div>
<% end %>

app/views/listings/_listing.html.erb
<div id="<%= dom_id listing %>">
  <p>
    <strong>Company:</strong>
    <%= listing.company %>
  </p>

  <p>
    <strong>Listing date:</strong>
    <%= listing.listingDate %>
  </p>

  <p>
    <strong>Contact:</strong>
    <%= listing.contact %>
  </p>

  <p>
    <strong>Activities:</strong>
    <%= listing.activities %>
  </p>

  <p>
    <strong>Price:</strong>
    <%= listing.price %>
  </p>

  <p>
    <strong>Code:</strong>
    <%= listing.code %>
  </p>

  <p>
    <strong>Capital:</strong>
    <%= listing.capital %>
  </p>

  <p>
    <strong>Close:</strong>
    <%= listing.close %>
  </p>

  <p>
    <strong>Underwriter:</strong>
    <%= listing.underwriter %>
  </p>

</div>

app/views/listings/edit.html.erb
<h1>Editing listing</h1>

<%= render "form", listing: @listing %>

<br>

<div>
  <%= link_to "Show this listing", @listing %> |
  <%= link_to "Back to listings", listings_path %>
</div>

app/views/listings/index.html.erb
<p style="color: green"><%= notice %></p>

<h1>Listings</h1>

<div id="listings">
  <% @listings.each do |listing| %>
    <%= render listing %>
    <p>
      <%= link_to "Show this listing", listing %>
    </p>
  <% end %>
</div>

<%= link_to "New listing", new_listing_path %>

app/views/listings/new.html.erb
<h1>New listing</h1>

<%= render "form", listing: @listing %>

<br>

<div>
  <%= link_to "Back to listings", listings_path %>
</div>

app/views/listings/show.html.erb
<p style="color: green"><%= notice %></p>

<%= render @listing %>

<div>
  <%= link_to "Edit this listing", edit_listing_path(@listing) %> |
  <%= link_to "Back to listings", listings_path %>

  <%= button_to "Destroy this listing", @listing, method: :delete %>
</div>

app/views/users/_form.html.erb
<%= form_with(model: user) do |form| %>

  <!-- This part is the bootstrap card -->

  <div class="card mb-3 bg-transparent text-bg-dark" style="width: 20rem;">
    <div class="row g-0">
      <div class="col-md-4">
        <img src="man.jpg" class="card-img-top">    <!-- Place the image at the top of the card -->
      </div>
      <div class="col-md-8">
        <div class="card-body">
          <h5 class="card-title">Stay current with all IPOs that are about to occur on the Austrailan Stock Exchange.</h5>
          <p class="card-text">Regular emails covering all the information you need to research current ASX IPOs.</p>    
        </div>
      </div>
    </div>
  
    <%= form.email_field :email, 
                        placeholder: "Your email address here ...", 
                        required: true %>  
                                                
    <%= form.button "Yes please", type: "submit", :class=> "btn btn-primary" %>
    <%= form.button "Unsubscribe me", type: "submit", :class=> "btn btn-danger" %>
    
    

    </div>
  
<% end %>

app/views/users/_user.html.erb
<div id="<%= dom_id user %>">
  <p>
    <strong>Email address on file:</strong>
    <%= user.email %>
  </p>

</div>

app/views/users/new.html.erb
<h1>New user</h1>

<%= render "form", user: @user %>

app/views/users/show.html.erb
<p style="color: green"><%= notice %></p>

<%= render @user %>

<div>
  <%= link_to "Edit this user", edit_user_path(@user) %> |
  <%= link_to "Back to users", users_path %>

  <%= button_to "Destroy this user", @user, method: :delete %>
</div>